# Generated by Django 4.2.16 on 2024-12-09 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('reading_time', models.CharField(max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
