# Generated by Django 4.2.17 on 2025-01-29 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_blogsubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phoneNumber', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
